[package]
name = "identity_registry"
authors = [""]
compiler_version = ">=0.25.0"
type = "contract"

[dependencies]
aztec = { git = 'https://github.com/AztecProtocol/aztec-packages/', tag = 'v0.85.0-alpha-testnet.2', directory = 'noir-projects/aztec-nr/aztec' }
