
/* Autogenerated file, do not edit! */

/* eslint-disable */
import {
  type AbiType,
  AztecAddress,
  type AztecAddressLike,
  CompleteAddress,
  Contract,
  type ContractArtifact,
  ContractBase,
  ContractFunctionInteraction,
  type ContractInstanceWithAddress,
  type ContractMethod,
  type ContractStorageLayout,
  type ContractNotes,
  decodeFromAbi,
  DeployMethod,
  EthAddress,
  type EthAddressLike,
  EventSelector,
  type FieldLike,
  Fr,
  type FunctionSelectorLike,
  loadContractArtifact,
  loadContractArtifactForPublic,
  type NoirCompiledContract,
  NoteSelector,
  Point,
  type PublicKey,
  PublicKeys,
  type Wallet,
  type U128Like,
  type WrappedFieldLike,
} from '@aztec/aztec.js';
//@ts-ignore
import IdentityRegistryContractArtifactJson from '../identityRegistry/target/identity_registry-IdentityRegistry.json' assert { type: 'json' };
export const IdentityRegistryContractArtifact = loadContractArtifact(IdentityRegistryContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract IdentityRegistry;
 */
export class IdentityRegistryContract extends ContractBase {
  
  private constructor(
    instance: ContractInstanceWithAddress,
    wallet: Wallet,
  ) {
    super(instance, IdentityRegistryContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A promise that resolves to a new Contract instance.
   */
  public static async at(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    return Contract.at(address, IdentityRegistryContract.artifact, wallet) as Promise<IdentityRegistryContract>;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, admin: AztecAddressLike) {
    return new DeployMethod<IdentityRegistryContract>(PublicKeys.default(), wallet, IdentityRegistryContractArtifact, IdentityRegistryContract.at, Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, admin: AztecAddressLike) {
    return new DeployMethod<IdentityRegistryContract>(publicKeys, wallet, IdentityRegistryContractArtifact, IdentityRegistryContract.at, Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof IdentityRegistryContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<IdentityRegistryContract['methods'][M]>
  ) {
    return new DeployMethod<IdentityRegistryContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      IdentityRegistryContractArtifact,
      IdentityRegistryContract.at,
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return IdentityRegistryContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(IdentityRegistryContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'admin' | 'zkPassportIDtoAddress' | 'addressToZKPassportID'> {
      return {
        admin: {
      slot: new Fr(1n),
    },
zkPassportIDtoAddress: {
      slot: new Fr(2n),
    },
addressToZKPassportID: {
      slot: new Fr(3n),
    }
      } as ContractStorageLayout<'admin' | 'zkPassportIDtoAddress' | 'addressToZKPassportID'>;
    }
    

  

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** constructor(admin: struct) */
    constructor: ((admin: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_address_from_zkID(zkID: field) */
    get_address_from_zkID: ((zkID: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_zkID_from_address(address: struct) */
    get_zkID_from_address: ((address: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** is_valid_address(address: struct) */
    is_valid_address: ((address: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** is_valid_zkID(zkID: field) */
    is_valid_zkID: ((zkID: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** remove_zkID_with_address() */
    remove_zkID_with_address: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_notes() */
    sync_notes: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** verify_zkID(circuitInputs: struct, zk_id: field, add_zkID: boolean, remove_zkID: boolean) */
    verify_zkID: ((circuitInputs: { vkeys: { vkey_a: FieldLike[], vkey_b: FieldLike[], vkey_c: FieldLike[], vkey_d: FieldLike[] }, proofs: { proof_a: FieldLike[], proof_b: FieldLike[], proof_c: FieldLike[], proof_d: FieldLike[] }, public_inputs: { input_a: FieldLike[], input_b: FieldLike[], input_c: FieldLike[], input_d: FieldLike[] } }, zk_id: FieldLike, add_zkID: boolean, remove_zkID: boolean) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
